image: registry.cn-beijing.aliyuncs.com/minerva/cibase:2.6.0

stages:
  - mvn-package
  - mvn-deploy

maven-test-branches:
  stage: mvn-package
  script:
    - git_merge master
  only:
    - /^bugfix-.*$/
    - /^feature-.*$/

maven-build:
  stage: mvn-package
  script:
    #    - update_pom_version
    - mvn clean package -U -DskipTests=false

maven-deploy:
  stage: mvn-deploy
  script:
    - maven_deploy
  only:
    - master
    - tags


.auto_devops: &auto_devops |
  echo "link devops server ${MINERVA_URL}..."
  sleep 5
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 30 -w %{http_code} "${MINERVA_URL}/devops/ci?token=${Token}&type=microservice"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh
  function docker_build(){
      cp /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar ${1:-"src/main/docker"}/app.jar || true
      docker login -u ${DOCKER_USER} -p ${DOCKER_PWD} ${DOCKER_REGISTRY}
      docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} ${1:-"src/main/docker"}
      docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
      rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
  }

before_script:
  - *auto_devops

